version: "3.8"
services:
  load-balancer:
    build: .
    container_name: load_balancer
    networks:
      mpi_network:
        ipv4_address: 172.20.128.2
    ports:
      - "22"
    command: ["/key_db/entrypoint.sh"]
  replica-1:
    build: .
    container_name: replica-1
    networks:
      mpi_network:
        ipv4_address: 172.20.128.3
    ports:
      - "22"
    entrypoint: ["/bin/sh", "-c"]
    command: ["service ssh start && tail -f /dev/null"]
  replica-2:
    build: .
    container_name: replica-2
    networks:
      mpi_network:
        ipv4_address: 172.20.128.4
    ports:
      - "22"
    entrypoint: ["/bin/sh", "-c"]
    command: ["service ssh start && tail -f /dev/null"]
  client-1:
    build: .
    container_name: client-1
    networks:
      mpi_network:
        ipv4_address: 172.20.128.5
    ports:
      - "22"
    entrypoint: ["/bin/sh", "-c"]
    command: ["service ssh start && tail -f /dev/null"]
  client-2:
    build: .
    container_name: client-2
    networks:
      mpi_network:
        ipv4_address: 172.20.128.6
    ports:
      - "22"
    entrypoint: ["/bin/sh", "-c"]
    command: ["service ssh start && tail -f /dev/null"]
  client-3:
    build: .
    container_name: client-3
    networks:
      mpi_network:
        ipv4_address: 172.20.128.7
    ports:
      - "22"
    entrypoint: ["/bin/sh", "-c"]
    command: ["service ssh start && tail -f /dev/null"]
networks:
  mpi_network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
